version: 0.2

env:
  variables:
    ARTIFACT_BUCKET: "jr-amz-test"
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - sam build --use-container
  post_build:
    commands:
      - sam package --output-template-file packaged-template.yml --s3-bucket $ARTIFACT_BUCKET
artifacts:
  files:
    - packaged-template.yml
