version: 0.0
containers:
    LambdaFunctions:
        phases:
            during_build:
                commands:
                    - cd src/data-processor-1 && pwd && npm install async marked
                    - cd src/data-processor-2 && npm install  async marked && ls 
                    - aws cloudformation package --template $INPUT_FILE --s3-bucket $S3_BUCKET --output-template post-sam.yaml
        artifacts:
            files:
                - post-sam.yaml
